remote_theme: mmistakes/so-simple-theme
#theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Recovery"
description: "Be kind to your body, you only have one"
# baseurl: "/" # the subpath of your site, e.g. "/blog"
# url: 
# logo: "/images/logo.png" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username:  # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
  nutrition_facts:
    output: true
    permalink: /:collection/:path/
  routines:
    output: true
    permalink: /:collection/:path/
  stretching:
    output: true
    permalink: /:collection/:path/



# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_nutrition_facts"
      type: nutrition_facts
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_routines"
      type: routines
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_stretching"
      type: stretching
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Maddy Robinette
  picture: 
  email:
  twitter: 
